name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.0
    - name: Install dependencies
      run: dotnet restore src/AbletonConvert.csproj
    - name: Build
      run: dotnet build src/AbletonConvert.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test src/AbletonConvert.csproj --no-restore --verbosity normal
